import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ReactQueryProvider } from './providers/ReactQueryProvider';

import { NavigationDrawer } from '@/components/NavigationDrawer';
import PlayerWrapper from '@/components/Player';

import '../styles/globals.css';

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${pretendard.variable}`}>
      <body className={`${pretendard.className}`}>
        <ReactQueryProvider>
          <main className='md:ml-[130px] px-6 py-15 md:p-5 min-h-screen w-full md:w-[calc(100%-130px)]'>
            {children}
          </main>
          <NavigationDrawer />
          <PlayerWrapper />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
