import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import { ReactQueryProvider } from './providers/ReactQueryProvider';
import { DBProvider } from './providers/DBProvider';

import { NavigationDrawer } from '@/components/NavigationDrawer';
import PlayerWrapper from '@/components/Player';

import '../styles/globals.css';
import ModalRoot from '@/components/ModalRoot';

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${pretendard.variable}`}>
      <body className={`${pretendard.className}`}>
        <DBProvider>
          <ReactQueryProvider>
            <main className='md:ml-[130px] px-6 py-15 md:p-5 min-h-screen w-full md:w-[calc(100%-130px)]'>
              {children}
              <PlayerWrapper />
            </main>
            <NavigationDrawer />
            <ModalRoot />

            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </DBProvider>
      </body>
    </html>
  );
}
